### ISSUE TITLE
Repository contains not so useful files and directories which can be ignored in .gitignore

### ISSUE THREAD

**Issue by coderero** [vishesh9131/CoreRec#1]
Hi @vishesh9131,

I'm opening this issue regarding the bad structure and no use of .gitignore file in the project which is essential when you want not to include non useful files in your repository. This is not necessary if project is at low scale but project like CoreRec it is really important to do these changes because the non useful files may add additional bugs or unpredictable behaviours while contributing on contributors machine. These issues can be addressed in this repository I may open a pull request in near future to address this issue.

Thank you.

**Comment by vishesh9131** [comment]
Hey,
Thank you for pointing this out. I will update the .gitignore file to ensure non-essential files are excluded from the repository. This will help maintain a clean project structure and prevent any potential issues for contributors. Feel free to open a pull request if you have any specific suggestions.

Thanks again for your input!
